"""initial schema

Revision ID: 134594173e32
Revises: 
Create Date: 2026-07-08 11:47:37.910891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134594173e32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('isin', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('instrument_type', sa.String(length=64), nullable=True),
    sa.Column('segment', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('total_shares', sa.Float(), nullable=True),
    sa.Column('nominal_value', sa.Float(), nullable=True),
    sa.Column('share_capital', sa.Float(), nullable=True),
    sa.Column('trade_start_date', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_symbol'), 'companies', ['symbol'], unique=True)
    op.create_table('crawl_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_key', sa.String(length=255), nullable=False),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('last_modified', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_metadata_resource_key'), 'crawl_metadata', ['resource_key'], unique=True)
    op.create_table('daily_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('var_pct', sa.Float(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('avg', sa.Float(), nullable=True),
    sa.Column('value_ron', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('trades', sa.Float(), nullable=True),
    sa.Column('market', sa.String(length=64), nullable=True),
    sa.Column('last_time', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_daily_price')
    )
    op.create_index(op.f('ix_daily_prices_date'), 'daily_prices', ['date'], unique=False)
    op.create_index(op.f('ix_daily_prices_symbol'), 'daily_prices', ['symbol'], unique=False)
    op.create_table('dividends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('yield_pct', sa.Float(), nullable=True),
    sa.Column('ex_date', sa.String(length=32), nullable=True),
    sa.Column('pay_date', sa.String(length=32), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dividends_symbol'), 'dividends', ['symbol'], unique=False)
    op.create_table('filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'url', name='uq_filing')
    )
    op.create_index(op.f('ix_filings_symbol'), 'filings', ['symbol'], unique=False)
    op.create_table('financial_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=32), nullable=True),
    sa.Column('statement_type', sa.String(length=64), nullable=True),
    sa.Column('line_item', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('source_filing', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_statements_symbol'), 'financial_statements', ['symbol'], unique=False)
    op.create_table('index_constituents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_name', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('shares_issued', sa.Float(), nullable=True),
    sa.Column('ref_price', sa.Float(), nullable=True),
    sa.Column('free_float_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_name', 'symbol', name='uq_index_constituent')
    )
    op.create_index(op.f('ix_index_constituents_index_name'), 'index_constituents', ['index_name'], unique=False)
    op.create_index(op.f('ix_index_constituents_symbol'), 'index_constituents', ['symbol'], unique=False)
    op.create_table('indices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indices_name'), 'indices', ['name'], unique=True)
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_symbol'), 'news', ['symbol'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('isin', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_symbol'), 'symbols', ['symbol'], unique=True)
    op.create_table('financial_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('pbv', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('div_yield', sa.Float(), nullable=True),
    sa.Column('dividend', sa.Float(), nullable=True),
    sa.Column('reference_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_metrics_as_of'), 'financial_metrics', ['as_of'], unique=False)
    op.create_table('shareholders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('holder', sa.String(length=255), nullable=False),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shareholders')
    op.drop_index(op.f('ix_financial_metrics_as_of'), table_name='financial_metrics')
    op.drop_table('financial_metrics')
    op.drop_index(op.f('ix_symbols_symbol'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_news_symbol'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_indices_name'), table_name='indices')
    op.drop_table('indices')
    op.drop_index(op.f('ix_index_constituents_symbol'), table_name='index_constituents')
    op.drop_index(op.f('ix_index_constituents_index_name'), table_name='index_constituents')
    op.drop_table('index_constituents')
    op.drop_index(op.f('ix_financial_statements_symbol'), table_name='financial_statements')
    op.drop_table('financial_statements')
    op.drop_index(op.f('ix_filings_symbol'), table_name='filings')
    op.drop_table('filings')
    op.drop_index(op.f('ix_dividends_symbol'), table_name='dividends')
    op.drop_table('dividends')
    op.drop_index(op.f('ix_daily_prices_symbol'), table_name='daily_prices')
    op.drop_index(op.f('ix_daily_prices_date'), table_name='daily_prices')
    op.drop_table('daily_prices')
    op.drop_index(op.f('ix_crawl_metadata_resource_key'), table_name='crawl_metadata')
    op.drop_table('crawl_metadata')
    op.drop_index(op.f('ix_companies_symbol'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
